apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
        - image: hasura/graphql-engine:v2.22.1
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "okampus.postgresSecret" . }}
                  key: db
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "hasura.postgresSecret" . }}
                  key: hasuraDb
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
