apiVersion: v1
kind: Service
metadata:
  name: {{ include "hasura.name" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hasura.service.type }}
  ports:
    - name: hasura
      port: {{ .Values.hasura.service.port }}
      targetPort: {{ .Values.hasura.service.targetPort }}
      protocol: TCP
  selector: {{- include "hasura.selectorLabels" . | nindent 4 -}}
