apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hasura.name" . }}
  labels: {{- include "hasura.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "hasura.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      creationTimestamp: null
      labels: {{- include "hasura.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: hasura/graphql-engine:v2.22.1
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "hasura.postgresSecret" . }}
                  key: db
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "hasura.postgresSecret" . }}
                  key: hasuraDb
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
          ports:
            - name: hasura
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 2
            httpGet:
              path: /healthz
              port: hasura
          startupProbe:
            failureThreshold: 15
            periodSeconds: 5
            timeoutSeconds: 2
            httpGet:
              path: /healthz
              port: hasura
          resources: {{- toYaml .Values.hasura.resources | nindent 12 -}}

