apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "okampus.configMap" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  BASE_TENANT_ID: {{ .Values.okampus.baseTenant.name }}
  BASE_DOMAIN: {{ .Values.okampus.baseUrl }}
  FRONTEND_ORIGIN_URL: {{ .Values.okampus.frontendUrl }}
  PSQL_HOST: {{ .Values.okampus.db.host | quote }}
  PSQL_PORT: {{ .Values.okampus.db.port | quote }}
  ORM_SEEDING_ENABLED: "true"
  REDIS_HOST: {{ .Values.okampus.redis.host | default (printf "%s-master.%s.svc.cluster.local" .Values.redis.fullnameOverride .Release.Namespace) }}
  REDIS_PORT: {{ .Values.okampus.redis.port | quote }}
  SENTRY_ENABLED: {{ not (empty .Values.sentryDSN) | quote }}
  SENTRY_DSN: {{ .Values.sentryDSN | default "" | quote }}
  S3_ENABLED: {{ .Values.okampus.s3.enabled | quote }}
  S3_ENDPOINT: {{ .Values.okampus.s3.endpoint | quote }}
  S3_REGION: {{ .Values.okampus.s3.region | quote }}
  S3_BUCKET_NAME_ATTACHMENTS: {{ .Values.okampus.s3.bucketNames.attachments | quote }}
  S3_BUCKET_NAME_ACTOR_IMAGES: {{ .Values.okampus.s3.bucketNames.actorImages | quote }}
  S3_BUCKET_NAME_ACTOR_DOCUMENTS: {{ .Values.okampus.s3.bucketNames.actorDocuments | quote }}
  S3_UPLOAD_MAX_SIZE: {{ .Values.okampus.s3.uploadMaxSize | int64 | quote }}
  MEILISEARCH_ENABLED: {{ .Values.okampus.meilisearch.enabled | quote }}
  MEILISEARCH_HOST: {{ printf "http://%s-%s.%s.svc.cluster.local:7700" (include "okampus.name" .) .Values.meilisearch.nameOverride .Release.Namespace }}
  NOVU_ENABLED: {{ .Values.okampus.novu.enabled | quote }}
  HASURA_GRAPHQL_ENDPOINT: {{ printf "http://%s.%s.svc.cluster.local:8080" (include "hasura.name" .)  .Release.Namespace }}
  {{- if .Values.okampus.preprod -}}
  {{- end -}}
