apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.dbUniversalSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "PSQL_UNIVERSAL_DB_DATABASE" "name" "PSQL_UNIVERSAL_DB_USERNAME" "user" "PSQL_UNIVERSAL_DB_PASSWORD" "password"  -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.dbUniversalSecret" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  PSQL_CONNECTION_STRING: {{ ternary (get $secretData "PSQL_CONNECTION_STRING") (((printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" (.Values.okampus.db.universal.user | urlquery) (.Values.okampus.db.universal.password | urlquery) .Values.okampus.db.universal.host (.Values.okampus.db.universal.port | toString) .Values.okampus.db.universal.name) | default "empty") | b64enc) (or (empty .Values.okampus.db.universal.user) (empty .Values.okampus.db.universal.password) (empty .Values.okampus.db.universal.host) (empty .Values.okampus.db.universal.port) (empty .Values.okampus.db.universal.name)) }}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ternary ((get $.Values.okampus.db.universal $val) | b64enc) ((get $secretData $key) | default ("empty" | b64enc)) (not (empty (get $.Values.okampus.db.universal $val))) }}
  {{- end -}}