apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.novuSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.okampus.novu.enabled -}}
  {{- $keys := dict "NOVU_API_KEY" "apiKey" "NOVU_APP_ID" "appId" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.novuSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ternary ((get $.Values.okampus.novu $val) | b64enc) ((get $secretData $key) | default ("empty" | b64enc)) (not (empty (get $.Values.okampus.novu $val))) }}
  {{- end -}}
  {{- end -}}