apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.vercel" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "VERCEL_PROJECT_ID" "projectId" "VERCEL_TEAM_ID" "teamId" "VERCEL_ACCESS_TOKEN" "accessToken" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "hasura.vercel" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ternary (get $secretData $key) (((get $.Values.hasura.vercel $val)  | default "empty") | b64enc) (not (empty (get $secretData $key))) }}
  {{- end -}}