apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.baseTenantSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "BASE_TENANT_DOMAIN" "domain" "BASE_TENANT_OIDC_ENABLED" "enabled" "BASE_TENANT_OIDC_NAME" "name" "BASE_TENANT_OIDC_CLIENT_ID" "clientId" "BASE_TENANT_OIDC_CLIENT_SECRET" "clientSecret" "BASE_TENANT_OIDC_DISCOVERY_URL" "discoveryUrl" "BASE_TENANT_OIDC_SCOPES" "scopes" "BASE_TENANT_OIDC_CALLBACK_URI" "callbackUri" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.baseTenantSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ternary (get $secretData $key) (((get $.Values.okampus.baseTenant.oidc $val)  | default "empty") | b64enc) (get $secretData $key) }}
  {{- end -}}