apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.postgresSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.postgresSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict }}
  db: {{ ternary (get $secretData "db") ((printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" (.Values.okampus.db.user | urlquery) (.Values.okampus.db.password | urlquery) .Values.okampus.db.host (.Values.okampus.db.port | toString) .Values.okampus.db.name) | b64enc) (or (empty .Values.okampus.db.password) (or (empty .Values.okampus.db.name) (or (empty .Values.okampus.db.user) (or (empty .Values.okampus.db.host) (empty .Values.okampus.db.port))))) }}