apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.s3Secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "S3_ACCESS_KEY_ID" "key" "S3_SECRET_ACCESS_KEY" "secret" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.s3Secret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ((get $.Values.app.s3 $val) | default "empty" | b64enc) | default (get $secretData $key) }}
  {{- end -}}