apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.anonSecret" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "ANON_ACCOUNT_USERNAME" "username" "ANON_ACCOUNT_EMAIL" "email" "ANON_ACCOUNT_FIRST_NAME" "firstName" "ANON_ACCOUNT_LAST_NAME" "lastName" "ANON_ACCOUNT_PASSWORD" "password" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.anonSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ (get $secretData $key) | default (((get $.Values.app.anon $val) | default (randAlphaNum 64)) | b64enc) }}
  {{- end -}}