apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.keysSecret" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "ACCESS_TOKEN_SECRET" "accessToken" "REFRESH_TOKEN_SECRET" "refreshToken" "WS_TOKEN_SECRET" "wsToken" "COOKIE_SIGNATURE_SECRET" "cookieSignature" "SESSION_SECRET" "session" "BOT_TOKEN_SECRET" "botToken" "CRYPTO_PEPPER_SECRET" "cryptoPepper" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.keysSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ (get $secretData $key) | default (((get $.Values.app.secrets $val) | default (randAlphaNum 32)) | b64enc ) }}
  {{- end -}}
