apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.postgresSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "PSQL_DATABASE" "name" "PSQL_USERNAME" "user" "PSQL_PASSWORD" "password"  -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.postgresSecret" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  PSQL_CONNECTION_STRING: {{ ternary (get $secretData "PSQL_CONNECTION_STRING") (((printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" (.Values.okampus.db.user | urlquery) (.Values.okampus.db.password | urlquery) .Values.okampus.db.host (.Values.okampus.db.port | toString) .Values.okampus.db.name) | (default "empty" | quote)) | b64enc) (or (empty .Values.okampus.db.user) (empty .Values.okampus.db.password) (empty .Values.okampus.db.host) (empty .Values.okampus.db.port) (empty .Values.okampus.db.name)) }}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ternary ((get $.Values.okampus.db $val) | b64enc) ((get $secretData $key) | default ("empty" | b64enc)) (not (empty (get $.Values.okampus.db $val))) }}
  {{- end -}}