apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.dbSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "MIKRO_ORM_DB_NAME" "name" "MIKRO_ORM_USER" "user" "MIKRO_ORM_PASSWORD" "password" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.dbSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ((get $.Values.app.db $val) | default "" | b64enc) | default (get $secretData $key) }}
  {{- end -}}