apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.postgreSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.postgreSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict }}
  db: {{ ternary (get $secretData "db") ((printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" .Values.app.db.user .Values.app.db.password .Values.app.db.host (.Values.app.db.port | toString) .Values.app.db.name) | b64enc) (or (empty .Values.app.db.password) (or (empty .Values.app.db.name) (or (empty .Values.app.db.user) (or (empty .Values.app.db.host) (empty .Values.app.db.port))))) }}