apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.adminSecret" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := dict "ADMIN_ACCOUNT_PASSWORD" "password" -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.adminSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- range $key, $val := $keys -}}
  {{ $key | nindent 2 -}}: {{ ternary ((get $.Values.okampus.admin $val) | b64enc) ((get $secretData $key) | default ((printf "default-%s" (randAlphaNum 64)) | b64enc)) (not (empty (get $.Values.okampus.admin $val))) }}
  {{- end -}}