apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okampus.tsSecret" . }}
  labels:
    {{- include "okampus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "okampus.tsSecret" .)) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- $tsSecret := ((get $secretData "TYPESENSE_API_KEY") | default ((.Values.app.typesense.apiKey  | default (randAlphaNum 64)) | b64enc )) }}
  TYPESENSE_API_KEY: {{ $tsSecret }}
  typesense-apikey: {{ $tsSecret }}
