apiVersion: v2
appVersion: 659b01147180275b6fb62b44e2265a4e433c4295
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.0.10
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.1.38
description: Student platform & digital workspace for schools
name: okampus
type: application
version: 0.6.37
