apiVersion: v2
appVersion: 4672f27d70702f60e3c0f5b1a3e4e7ac7b6230ae
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.0.10
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.1.38
description: Student platform & digital workspace for schools
name: okampus
type: application
version: 0.5.8
