apiVersion: v2
name: okampus
description: Student platform & digital workspace for schools
type: application
version: 1.4.17
appVersion: 454a2d1adf670f0e810610a870bbd05c2a65bdde
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.2
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.2.4
