apiVersion: v2
name: okampus
description: Student platform & digital workspace for schools
type: application
version: 1.5.5
appVersion: 449f0ab5a91f102f37c25134efa522d6f495ee93
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.2
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.2.4
