apiVersion: v2
name: okampus
description: Student platform & digital workspace for schools
type: application
version: 1.2.8
appVersion: 0cac464da33c2672c7a46e89e66063e91eadd1ad
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.1
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.2.4
