apiVersion: v2
name: okampus
description: Student platform & digital workspace for schools
type: application
version: 1.1.58
appVersion: 00410b6553a3a3f672362fa979e069656a9ccb51
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.14.3
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.2.2
