# Default values for okampus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
replicaCount: 1
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1111
  # fsGroup: 2000

nodeSelector: {}
affinity: {}
tolerations: []

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

imagePullSecrets: []
image:
  repository: rg.fr-par.scw.cloud/okampus/okampus
  pullPolicy: IfNotPresent
  tag:

env: []
envFrom:

preprod: false
okampus:
  baseUrl: okampus.fr
  fqdn: api.okampus.fr
  frontendUrl: efrei.okampus.fr

  baseTenant:
    name: okampus
    oidc:
      enabled: "false"
      clientId:
      clientSecret:
      discoveryUrl: "https://oauth2service.com/.well-known/openid-configuration"
      scopes: "openid profile"
      callbackUri: "https://api.okampus.fr/auth/tenant/callback"

  admin:
    password:

  db:
    host:
    port: 5432
    name: okampus
    user: okampus-admin
    password:

  redis:
    host:
    port: 6379

  novu:
    enabled: true
    apiKey:
    appId:

  s3:
    enabled: true
    bucketNames:
      attachments: okampus-attachments
      orgImages: okampus-org-images
      orgDocuments: okampus-org-documents
      orgVideos: okampus-org-videos
      userImages: okampus-user-images

    key:
    secret:
    region:
    endpoint:

  secrets:
    accessToken:
    refreshToken:
    wsToken:
    cookieSignature:
    session:
    botToken:
    cryptoPepper:

  sentryDSN: https://a@b.ingest.sentry.io/1234


hasura:
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081

  db:
    host:
    port: 5432
    name: hasura-metadata
    user: hasura-admin
    password:

  name: hasura
  fqdn: hasura.okampus.fr
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

meilisearch:
  # WARNING: This needs to be changed manually, in the format <appName-meilisearch>
  nameOverride: okampus-meilisearch
  image:
    tag: v0.28.1
  environment:
    MEILI_ENV: production
  persistence:
    enabled: true

  url: meilisearch.okampus.fr
  command:
    - /bin/sh
    - -c
    - /bin/meilisearch
    - --enable-auto-batching

# Redis config
redis:
  fullnameOverride: okampus-redis

  auth:
    enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false
  master:
    persistence:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        instance: primary
