# Default values for hasura.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
replicaCount: 1
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1111
  # fsGroup: 2000

nodeSelector: {}
affinity: {}
tolerations: []

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

imagePullSecrets: []
image:
  repository: rg.fr-par.scw.cloud/okampus/hasura
  pullPolicy: IfNotPresent
  tag:

env: []
envFrom:

sentryDSN:
preprod: false

hasura:
  name: hasura
  fqdn: hasura.hasura.fr
  vercel:
    projectId:
    teamId:
    accessToken:

  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  service:
    type: ClusterIP
    portName: hasura
    port: 8080
    targetPort: 8080

meilisearch:
  # WARNING: This needs to be changed manually, in the format <appName-meilisearch>
  nameOverride: okampus-meilisearch
  image:
    tag: v0.28.1
  environment:
    MEILI_ENV: production
  persistence:
    enabled: true

  url: meilisearch.hasura.fr
  command:
    - /bin/sh
    - -c
    - /bin/meilisearch
    - --enable-auto-batching

# Redis config
redis:
  fullnameOverride: okampus-redis

  auth:
    enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false
  master:
    persistence:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        instance: primary
